graph LR

run.sh -. -p 3334 .-> bin/ediss.sh
bin/ediss.sh -.- oai
run.sh -. -p 3335 .-> bin/tubdok.sh
run.sh -. -p 3336 .-> bin/...

subgraph bin/ediss.sh
oai((OAI)) --> metha
metha --> 01oai(data/01_oai/ediss_$date.xml)
01oai -. openrefine-client .-> openrefine-container[OpenRefine<br>port 3334]
config(cfg/ediss/transformation.json) --> openrefine-container
openrefine-container --> 02transformed(data/02_transformed/ediss_$date.tsv)
02transformed -- curl --> solr((Solr core<br>local/external))
02transformed -- openrefine-client --> openrefine-service((OpenRefine<br>port 3333))
end
